#!/bin/bash
# Need to print out whether a helpful error if something fails

#tsc
export LOG_LEVEL=0   # Default log level is 0
export LOG_LEVEL=2   # here for testing
if [ $# == 1 ]; then # One command line argument
  if [ $1 == "install" ]; then
    echo "Installing required packages..."
    npm install # Install packages in userland
    echo "Installed required packages"
  elif [ $1 == "test" ]; then # Test
    #echo "Current log level is $LOG_LEVEL"
    echo "You chose test"
    # Call the test suite here
  else
    echo "Current log level is $LOG_LEVEL"
    echo "You passed $1" # URL_FILE
    echo "Compiling TypeScript files..."
    tsc
    if [ $? -ne 0 ]; then
      echo "TypeScript compilation failed. Exiting..."
      exit 1
    fi
    echo "Running JaveScript file..."
    node src/main.js $1
  fi
else # Not one command line argument
  echo "Invalid number of command line arguments"
fi
